# Generated by Django 2.2.4 on 2019-08-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impaque_caculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coemisonprofile',
            name='dummy',
        ),
        migrations.RemoveField(
            model_name='coemisonprofile',
            name='dumy',
        ),
    ]
