# Generated by Django 2.2.4 on 2019-08-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impaque_caculator', '0002_auto_20190813_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coemisonprofile',
            name='co_emission_metric',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
