# Generated by Django 2.2.4 on 2019-08-13 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('impaque_caculator', '0003_auto_20190813_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co2EmisonProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumption_metric', models.FloatField()),
                ('distance_travele', models.FloatField()),
                ('is_diesel', models.BooleanField()),
                ('co_emission_metric', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CoEmisonProfile',
        ),
    ]
