# Generated by Django 2.2.4 on 2019-08-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impaque_caculator', '0004_auto_20190813_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='co2emisonprofile',
            old_name='co_emission_metric',
            new_name='co2_emission_metric',
        ),
    ]
