# Generated by Django 2.2.4 on 2019-08-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impaque_caculator', '0006_auto_20190815_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engement',
            name='duration_of_the_engement',
        ),
        migrations.AddField(
            model_name='engement',
            name='distance',
            field=models.IntegerField(default=10, help_text='nomber of km traveld for that engement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engement',
            name='duration',
            field=models.IntegerField(default=5, help_text='duration of the engament in day'),
            preserve_default=False,
        ),
    ]
