# Generated by Django 2.2.4 on 2019-08-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impaque_caculator', '0007_auto_20190816_1650'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Engement',
            new_name='Engagement',
        ),
    ]
