# Generated by Django 2.2.4 on 2019-08-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impaque_caculator', '0008_auto_20190816_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='co2emisonprofile',
            name='is_diesel',
            field=models.CharField(choices=[('DI', 'diesel'), ('ES', 'esence')], default='ES', max_length=2),
        ),
    ]
