# Generated by Django 2.2.4 on 2019-09-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impaque_caculator', '0011_globalemisonmetric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagement',
            name='emison_metric',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
